# Generated by Django 5.0.1 on 2024-01-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_applications_posting_posting_poster_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='firstName',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applications',
            name='lastName',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
